items:
  SPC: command-palette:open
  TAB: editor:focus
  /: global-search:open
  ",": editor:context-menu
  "?": switcher:open

  w:
    description: Workspace
    items:
      TAB: editor:focus
      d: workspace:close
      f: file-explorer:open
      h: editor:focus-left
      l: editor:focus-right
      k: editor:focus-top
      j: editor:focus-bottom
      n: workspace:next-tab
      N: workspace:new-tab
      o: outline:open
      p: workspace:previous-tab
      P: workspace:toggle-pin
      s: workspace:split-horizontal
      S: workspace:toggle-stacked-tabs
      t: tag-pane:open
      u: workspace:undo-close-pane
      v: workspace:split-vertical
      L: app:toggle-left-sidebar
      r: app:toggle-right-sidebar
      R: app:toggle-ribbon
      w: workspace:open-in-new-window
      W: workspace:move-to-new-window

      x:
        description: Close
        items:
          g: workspace:close-tab-group
          G: workspace:close-others-tab-group
          t: workspace:close
          T: workspace:close-others
          w: workspace:close-window

       # workspace:goto-last-tab
       # workspace:goto-tab-1
       # workspace:goto-tab-2
       # workspace:goto-tab-3
       # workspace:goto-tab-4
       # workspace:goto-tab-5
       # workspace:goto-tab-6
       # workspace:goto-tab-7
       # workspace:goto-tab-8

       # workspace:show-trash


  f:
    description: File
    items:
      a: markdown:add-alias
      c: workspace:copy-path
      C: workspace:copy-url
      d: app:delete-file
      o: open-with-default-app:open
      O: open-with-default-app:show
      p: markdown:add-metadata-property
      P: markdown:edit-metadata-property
      r: editor:open-search-replace
      R: workspace:edit-file-title
      s: editor:save-file
      t: file-explorer:reveal-active-file
      T: tag-pane:open
      u: outline:open-for-current
      /: editor:open-search

      # markdown:clear-metadata-properties

  l:
    description: Layout
    items:

  x:
    description: Text
    items:
      b: editor:toggle-bold
      i: editor:toggle-italics
      c: editor:toggle-code
      C: editor:toggle-comments
      p: editor:insert-codeblock
      q: editor:toggle-blockquote
      s: editor:toggle-strikethrough
      l: editor:toggle-bullet-list
      H: editor:toggle-highlight
      M: editor:toggle-inline-math

      # editor:set-heading
      # editor:set-heading-0
      # editor:set-heading-1
      # editor:set-heading-2
      # editor:set-heading-3
      # editor:set-heading-4
      # editor:set-heading-5
      # editor:set-heading-6
      # editor:rename-heading

      # editor:swap-line-down
      # editor:swap-line-up

      # editor:clear-formatting
      # editor:context-menu
      # editor:delete-paragraph

      # editor:toggle-bullet-list
      # editor:toggle-checklist-status
      # editor:toggle-numbered-list
      # editor:cycle-list-checklist

  i:
    description: Insert
    items:
      a: editor:attach-file
      c: editor:insert-codeblock
      C: editor:insert-callout
      e: editor:insert-embed
      l: editor:insert-link
      L: editor:insert-wikilink
      m: editor:insert-mathblock
      r: editor:insert-horizontal-rule
      t: editor:insert-table
      T: editor:insert-tag

  t:
    description: Table
    items:
      h: editor:table-col-left
      l: editor:table-col-right
      k: editor:table-row-up
      j: editor:table-row-down
      c: editor:table-col-after
      C: editor:table-col-before
      r: editor:table-row-after
      R: editor:table-row-before
      v: editor:table-row-copy
      V: editor:table-col-copy
      i: editor:insert-table

      d:
        description: Delete
        items:
          c: editor:table-col-delete
          r: editor:table-row-delete

      a:
        description: Align
        items:
          c: editor:table-col-align-center
          l: editor:table-col-align-left
          r: editor:table-col-align-right

  v:
    description: View
    items:
      p: editor:toggle-source
      r: markdown:toggle-preview
      s: editor:toggle-spellcheck
      T: window:toggle-always-on-top

      # window:reset-zoom
      # window:zoom-in
      # window:zoom-out

